#!/usr/bin/env bash

# script to update eix cache with each sync
if [[ -e /var/cache/eix/portage.eix ]]; then
	rsync -ca /var/cache/eix/portage.eix /var/cache/eix/previous.eix;
fi

eix-update

if [[ -e /var/cache/eix/previous.eix ]]; then
	eix-diff;
fi
