# Tuned flags
COMMON_FLAGS="-march=native -O2 -pipe -flto"
# General flags
#COMMON_FLAGS="-O2 -pipe"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j8 -l9"
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=9 --quiet-build --verbose --complete-graph=y --with-bdeps=y --keep-going --deep --backtrack=30"
# xxx with-bdeps=y, see https://forums.gentoo.org/viewtopic-t-1037770-start-25.html

# emerge extremely low priority (to run in the background)
PORTAGE_SCHEDULING_POLICY="idle"

# latest
ACCEPT_KEYWORDS="~amd64"

# all licenses
ACCEPT_LICENSE="*"

# mirrors
GENTOO_MIRRORS="https://gentoo.osuosl.org/ https://mirror.leaseweb.com/gentoo/ rync://mirror.leaseweb.com/gentoo/ ftp://mirrors.rit.edu/gentoo/"

# gpu
MICROCODE_SIGNATURES="-s 0x000906e9"
VIDEO_CARDS="amdgpu radeonsi intel"

# misc drivers
INPUT_DEVICES="libinput"

# qemu
GRUB_PLATFORMS="efi-64"
QEMU_SOFTMMU_TARGETS="arm x86_64 sparc i386"
QEMU_USER_TARGETS="x86_64"

USE="v4l lto man verify-sig valgrind cjk X xwayland wayland gles2 zsh-completion ffmpeg \
     jack policykit postscript elogind dbus udev nss qml widgets minizip acl pulseaudio \
     vaapi \
     -bluetooth -systemd -telemetry -wifi -wext -networkmanager"

# NOTE: This stage was built with the bindist Use flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
